 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://dev.azure.com/BCSDevOps/Blue%20Bear%20Waste%20Systems/_git/BBWS%20Inventory%20Tracking'
    sourceVerifySSLCertificate: false
    sourceGitRepositoryPersonalAccessToken: "oatzfnpf5x2dqmoivbx5pmfreb4olsus2khbhy7vw4lwt2opi3ea"
    destinationGitRepositoryUri: 'https://github.com/halhamadahbcs/BBWSInventoryTracking.git'
    destinationGitRepositoryPersonalAccessToken: '$(DestinationKey)'
    destinationVerifySSLCertificate: false
